package org.firstinspires.ftc.teamcode.SharedFiles;



public class Constants {
    public static final String VUFORIAKEY = "AYoH7ev/////AAAAGfXsSDS/MkyPhjcE+faq/48h6DaEWZF/8SNzje0MAsK4UDuXARu6fcLc2aKpRcMDhGTEc1vD9tQDrA6oS0G/hjFHDyZZ6PElyBrQuNRFWrc6xKqk+XeAIgVDJic61ARKYpolBXMo+dT31h7j4C/7eNFrA3XFfp/mTlrX3fka8+LGbYpUoQv7LNqe+mnkBq06F41JWsLSaOddOYusZViRksxD/a1Zxu5vJf7BeuIqGw7emroUjVcieRRwcvKLPsEHKo6Mb5luudkJeVPtDJaPcHdtVejarnROLNn58v16LgzEbsTXSZvItjvzfrsnAkQiHVsN4XMQFoueOEm9QG4RhLvR4UMs1ab23WAph+14ulVP";

}
